name = "wedding-vow-ai-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-10"

[vars]
GEMINI_MODEL = "models/gemini-2.0-flash"

[env.local]
vars = { GEMINI_MODEL = "models/gemini-2.0-flash" }
